baseURL = "https://poke.digital/"
languageCode = "en-us"
title = "Poke"
enableEmoji = true
enableRobotsTXT = true
theme = "HugoMDL"
MetaDataFormat = "yaml"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  author = "Poke"
  avatar = "/poke-avatar.png"
  background = "/images/background.jpg"
  description = "A place to publish my incomprehensible ramblings" #meta description
  image = "/poke-avatar.png" #for frontpage profile card
  website = "poke.digital"
  github = "https://github.com/warp-poke/"
  copyrightyear = "2018"
  frontpageposts = 6 # number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
